version: '3.7'
services:
    web:
        image: 'node'
        container_name: simplytodo-web
        working_dir: /app
        volumes:
            - ./web:/app
        ports:
            - '80:5000'
        command: /bin/bash -c "yarn && yarn build && yarn serve -s build"
    backend:
        image: 'node'
        container_name: simplytodo-backend
        working_dir: /app
        volumes:
            - './backend:/app'
        ports:
            - '3333:3000'
        environment:
            - PORT=3000
        command: /bin/bash -c "yarn && yarn build && yarn typeorm migration:run && node dist/server.js"
