version: '3.7'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PATH_TO_PROJECT_DIR=web
        volumes:
            - './web:/app'
        ports:
            - '80:5000'
        environment:
            - NODE_ENV=production
        command: /bin/sh -c "yarn build && yarn serve -s build"
    backend:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PATH_TO_PROJECT_DIR=backend
        volumes:
            - './backend:/app'
        ports:
            - '3333:3000'
        environment:
            - NODE_ENV=production
            - PORT=3000
        command: /bin/sh -c "yarn build && yarn typeorm migration:run && node dist/server.js"
